base_url = "https://trunkrs.dev"

title = "Trunk | Build, bundle & ship your Rust WASM application to the web"

compile_sass = true
highlight_code = true
highlight_theme = "inspired-github"
build_search_index = true

theme = "juice"

# Custom variables go here.
[extra]
favicon = "rustacean-flat-happy.svg"
juice_logo_name = "Trunk"
juice_logo_path = "rustacean-flat-happy.svg"
juice_extra_menu = [
    { title = "Github", link = "https://github.com/thedodd/trunk"}
]
