[book]
title = "The Trunk Guide"
description = "Documention of Trunk, a web application bundler for Rust"
src = "src"

language = "en"

authors = ["Jens Reimann <ctron@dentrassi.de>"]

[build]
build-dir = "book/html"

[rust]
edition = "2021"

[output.html]
git-repository-url = "https://github.com/trunk-rs/trunk"
git-repository-icon = "fas-code-fork"
edit-url-template = "https://github.com/trunk-rs/trunk/edit/main/guide/{path}"

additional-css = [
    "theme/pagetoc.css"
]
additional-js = [
    "theme/pagetoc.js"
]

