name: Manual Brew
on:
  workflow_dispatch:
    inputs:
      tag-name:
        description: 'The git tag name to bump the formula to.'
        required: true

jobs:
  brew:
    name: Bump Brew Version
    runs-on: ubuntu-latest
    steps:
      - uses: mislav/bump-homebrew-formula-action@v3
        with:
          tag-name: ${{ github.event.inputs.tag-name }}
        env:
          COMMITTER_TOKEN: ${{ secrets.HOMEBREW_GITHUB_API_TOKEN }}
